cask_args appdir: '/Applications'

tap 'heroku/brew'
tap 'isen-ng/dotnet-sdk-versions'

brew 'ack' # alternative to grep
brew 'adns'
brew 'ansible'
brew 'autoconf'
brew 'automake'
brew 'amazon-ecs-cli'
brew 'direnv' # Used to auto-load .env files
brew 'docker'
brew 'docker-compose'
brew 'duti' # Tool for setting default applications for file types via cli
brew 'fileicon' # Used to assign custom file icons to files / folders
brew 'ghostscript'
brew 'git'
brew 'git-svn'
brew 'gnupg'
brew 'helm'
brew 'heroku'
brew 'htop'
brew 'hub'
brew 'imagemagick'
brew 'jenv'
brew 'kubernetes-cli'
brew 'lame' # mp3 encoder, needed for audacity
brew 'libevent'
brew 'libtiff'
brew 'mas'
brew 'mysql-client'
brew 'nvm' # we used to install node directly, like scrubs.
brew 'openssl'
brew 'pass'
brew 'postgresql'
brew 'pyenv'
brew 'rbenv'
brew 'redis'
brew 'ruby'
brew 'subversion'
brew 'sqlite'
brew 'terraform'
brew 'tesseract'
brew 'vim'
brew 'wget'
brew 'xpdf'
brew 'z'
brew 'zsh'
brew 'zsh-completions'

# Applications
cask 'audio-hijack'
cask 'alfred'
cask 'battle-net'
cask 'bitwarden'
cask 'brave-browser'
cask 'chromium', args: { "no-quarantine": true }
cask 'cyberduck'
cask 'discord'
cask 'dungeon-crawl-stone-soup-tiles'
cask 'firefox'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'iterm2'
cask 'temurin' # This is java (https://adoptium.net/)
cask 'little-snitch'
cask 'maestral'
cask 'micro-snitch'
cask 'microsoft-office'
cask 'omnifocus'
cask 'omnigraffle'
cask 'omnioutliner'
cask 'omniplan'
cask 'quicken'
cask 'rectangle'
cask 'signal'
cask 'slack'
cask 'steam'
cask 'steamcmd'
cask 'soundsource'
cask 'spotify'
cask 'swinsian'
cask 'transmit'
cask 'tor-browser'
cask 'thunderbird'
cask 'vlc'
cask 'vscodium'
cask 'zulip'
cask 'zoom'

# Fonts
cask 'font-fira-code'
cask 'font-inconsolata'
cask 'font-source-code-pro'
cask 'font-open-sans'
cask 'font-overpass'
