#!/usr/bin/env bash
set -e
source ~/.dotfiles/lib/functions.sh

###
# Maintains a "managed block" of host entries inside /etc/hosts.
#
# The block is assembled from two files:
#   - hosts/hosts        (shared, checked in) — safe-to-publish entries
#   - hosts/hosts.local  (private, gitignored) — don't-publish entries, optional
#
# Everything between the BEGIN/END markers is owned by this script: it is fully
# regenerated on each run, so the script is idempotent and safe to re-run. Lines
# outside the markers (localhost, Docker Desktop's section, etc.) are preserved.
###

hosts_file="/etc/hosts"
shared_file="$HOME/.dotfiles/hosts/hosts"
private_file="$HOME/.dotfiles/hosts/hosts.local"
begin_marker="# BEGIN DOTFILES MANAGED HOSTS"
end_marker="# END DOTFILES MANAGED HOSTS"

check_exists "$shared_file"

info "Building managed hosts block for ${hosts_file}"

# Assemble the desired block body from the shared file plus the optional overlay.
block_body="$(cat "$shared_file")"
if [ -f "$private_file" ]; then
	info "Including private overlay: ${private_file}"
	block_body="${block_body}"$'\n\n'"# --- private (hosts.local) ---"$'\n'"$(cat "$private_file")"
fi

# Build the desired /etc/hosts in a temp file:
#   1. everything currently in /etc/hosts EXCEPT any existing managed block
#   2. trailing blank lines trimmed (keeps re-runs from accumulating whitespace)
#   3. a freshly generated managed block appended
tmp="$(mktemp)"
sed "/^${begin_marker}$/,/^${end_marker}$/d" "$hosts_file" \
	| awk 'NF { last = NR } { line[NR] = $0 } END { for (i = 1; i <= last; i++) print line[i] }' \
		> "$tmp"

{
	printf '\n%s\n' "$begin_marker"
	printf '# Generated by ~/.dotfiles/hosts/install.sh — do not edit by hand.\n'
	printf '# Edit hosts/hosts (shared) or hosts/hosts.local (private), then re-run install.sh.\n'
	printf '%s\n' "$block_body"
	printf '%s\n' "$end_marker"
} >> "$tmp"

# Only touch /etc/hosts (and prompt for sudo) if something actually changed.
if cmp -s "$tmp" "$hosts_file"; then
	rm -f "$tmp"
	success "Hosts already up to date"
	exit 0
fi

info "Updating ${hosts_file} (a backup will be written to ${hosts_file}.dotfiles.bak)"
sudo cp "$hosts_file" "${hosts_file}.dotfiles.bak"
sudo cp "$tmp" "$hosts_file"
rm -f "$tmp"

success "Hosts updated"
